export enum notificationMessage {
    NOTIFICATION = 'NOTIFICATION',
    NOTIFICATION_READ = 'NOTIFICATION_READ',
    NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',
    NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',
    NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE',
    NOTIFICATION_ERROR = 'NOTIFICATION_ERROR',
}